

export default   [
    'Physician assistant',
    'Wellness coordinator','Healthcare consultant',
    'Community health worker',
    'Medical writer',
    'Nurse practitioner',
    'Medical secretary',
    'Patient advocate',
    'Medical records manager',
    'Clinical nurse educator',
    'Pharmaceutical sciences manager',
    'Assisted living director',
    'Medical transcriptionist',
    'Health educator',
    'Health information technician',
    'Clinical administrator',
    'Pharmacy manager',
    'Nursing administrative supervisor',
    'Dental office manager',
    'Occupational therapist',
    'Customer service representative',
    'Market researcher',
    'Advertising sales agent',
    'Marketing specialist',
    'Store manager',
    'Sales associate',
    'Regulatory affairs manager',
    'Social media strategist',
    'Digital community manager',
    'Market analyst',
    'Account manager',
    'Business development specialist',
    'Regional sales manager',
    'Brand ambassador',
    'International partnerships manager',
    'Content marketing coordinator',
    'Product marketing manager',
    'SEO specialist',
    'Marketing assistant',
    'Copywriter',
    'Web developer',
    'Computer support specialist',
    'User experience designer',
    'Information security analyst',
    'Mobile application developer',
    'Computer programmer',
    'Database administrator',
    'Operations analyst',
    'Network architect',
    'Cybersecurity specialist',
    'Network administrator',
    'Cloud engineer',
    'Front end developer',
    'Software engineer',
    'IT systems administrator',
    'Quantitative analyst',
    'Technical specialist',
    'Software integration engineer',
    'Intrusion detection specialist',
    'Data warehouse administrator',
    'Certified public accountant',
    'Compliance auditor',
    'Budget analyst',
    'Actuary',
    'Risk management specialist',
    'Underwriter',
    'Internal auditor',
    'Cost estimator',
    'Tax associate',
    'Compensation and benefits manager',
    'Loan officer',
    'Corporate accountant',
    'Financial advisor',
    'Credit analyst',
    'Forensic accountant',
    'Tax accountant',
    'Finance manager',
    'Cost accountant',
    'Investment manager',
    'Financial reporting manager',
    'Maintenance technician',
    'Journeyman carpenter',
    'Biosystems engineer',
    'Equipment operator',
    'Field service technician',
    'Manufacturing engineer',
    'Construction estimator',
    'Product scheduler',
    'Operations supervisor',
    'Facilities manager',
    'Safety coordinator',
    'HVAC installer',
    'Construction project administrator',
    'Construction inspector',
    'Construction foreman',
    'Environmental sustainability manager',
    'Job site superintendent',
    'Installation manager',
    'Construction surveyor',
    'Solar technician'
]